name: windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        #update: true
    - name: Install MSYS2 Dependencies
      run: |
        pwd
        ./scripts/msys2-install-dependencies.sh
    - name: Build OpenSCAD
      run: |
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake .. -DMPFR_LIBRARIES=libmpfr -DCMAKE_BUILD_TYPE=Release -DEXPERIMENTAL=ON -DSNAPSHOT=ON
        mingw32-make.exe -j2
    - name: Run Test Suite
      run: |
        cp -v /mingw64/bin/opengl32.dll build/
        cd tests
        ctest -j2 -E 'opencsgtest_issue1165|opencsgtest_issue1215|throwntogethertest_issue1089|throwntogethertest_issue1215|openscad-nonascii|import_3mf|3mfpngtest|3mfexport|pdfexporttest_centered'
    - name: Upload Test Result Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Test Result Report (Windows)
        path: |
          tests/output/
          tests/Testing/Temporary/*_report.html
